#include <quantapdf/quantapdf.h>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void check_impl(int ok,const char *expr,int line){if(!ok){fprintf(stderr,"%s:%d: check failed: %s\n",__FILE__,line,expr);exit(EXIT_FAILURE);}}
#define CHECK(x) check_impl((x),#x,__LINE__)
static int close_float(float a,float b){float d=a-b;if(d<0)d=-d;return d<0.01f;}

static void compile_surface(void)
{
    quantapdf_form *form=NULL;quantapdf_form_field_type type=QUANTAPDF_FORM_FIELD_UNKNOWN;quantapdf_form_value_presence presence=QUANTAPDF_FORM_VALUE_NOT_APPLICABLE;
    quantapdf_form_value_kind vk=QUANTAPDF_FORM_VALUE_UTF8;quantapdf_form_option_kind ok=QUANTAPDF_FORM_OPTION_BUTTON_STATE;quantapdf_form_field_info fi={0};
    quantapdf_form_value_info vi={0};quantapdf_form_option_info oi={0};quantapdf_form_widget_info wi={0};quantapdf_document *d=NULL;const char *s=NULL;size_t n=0,c=0;
    fi.struct_size=sizeof(fi);vi.struct_size=sizeof(vi);oi.struct_size=sizeof(oi);wi.struct_size=sizeof(wi);(void)type;(void)presence;(void)vk;(void)ok;
    if(0){(void)quantapdf_document_form(d,&form);(void)quantapdf_form_field_count(form,&c);(void)quantapdf_form_field_get_info(form,0,&fi);(void)quantapdf_form_field_name(form,0,&s,&n);(void)quantapdf_form_field_label(form,0,&s,&n);(void)quantapdf_form_field_value_get_info(form,0,0,&vi);(void)quantapdf_form_field_value_utf8(form,0,0,&s,&n);(void)quantapdf_form_field_option_get_info(form,0,0,&oi);(void)quantapdf_form_field_option_export(form,0,0,&s,&n);(void)quantapdf_form_field_option_display(form,0,0,&s,&n);(void)quantapdf_form_widget_count(form,&c);(void)quantapdf_form_widget_get_info(form,0,&wi);quantapdf_drop_form(form);}
}

static void expect_empty(const char *path){quantapdf_document *d=NULL;quantapdf_form *f=NULL;size_t a=99,b=99;CHECK(quantapdf_open(path,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);CHECK(f!=NULL);quantapdf_close(d);CHECK(quantapdf_form_field_count(f,&a)==QUANTAPDF_OK);CHECK(a==0);CHECK(quantapdf_form_widget_count(f,&b)==QUANTAPDF_OK);CHECK(b==0);quantapdf_drop_form(f);}
static void expect_string(const quantapdf_form *f,size_t i,int label,const char *e,int present){const char *s=(const char *)(uintptr_t)1;size_t n=99;quantapdf_status st=label?quantapdf_form_field_label(f,i,&s,&n):quantapdf_form_field_name(f,i,&s,&n);CHECK(st==QUANTAPDF_OK);if(!present){CHECK(s==NULL);CHECK(n==0);return;}CHECK(s!=NULL);CHECK(n==strlen(e));CHECK(memcmp(s,e,n)==0);CHECK(s[n]=='\0');}
static void expect_extract_status(const char *path,quantapdf_status expected){int sentinel=0;quantapdf_document *d=NULL;quantapdf_form *f=(quantapdf_form *)&sentinel;CHECK(quantapdf_open(path,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==expected);CHECK(f==NULL);quantapdf_close(d);}

static void test_api_shell(void){int sentinel=0;quantapdf_form *f=(quantapdf_form *)&sentinel;size_t c=99;const char *s=(const char *)&sentinel;size_t n=99;CHECK(QUANTAPDF_FORM_FIELD_UNKNOWN==0);CHECK(QUANTAPDF_FORM_FIELD_SIGNATURE==7);CHECK(QUANTAPDF_FORM_VALUE_NOT_APPLICABLE==0);CHECK(QUANTAPDF_FORM_VALUE_PRESENT==2);CHECK(QUANTAPDF_FORM_VALUE_UTF8==1);CHECK(QUANTAPDF_FORM_VALUE_OPTION==2);CHECK(QUANTAPDF_FORM_OPTION_BUTTON_STATE==1);CHECK(QUANTAPDF_FORM_OPTION_CHOICE==2);CHECK(quantapdf_document_form(NULL,&f)==QUANTAPDF_ERROR_ARGUMENT);CHECK(f==NULL);CHECK(quantapdf_document_form(NULL,NULL)==QUANTAPDF_ERROR_ARGUMENT);CHECK(quantapdf_form_field_count(NULL,&c)==QUANTAPDF_ERROR_ARGUMENT);CHECK(c==0);CHECK(quantapdf_form_widget_count(NULL,&c)==QUANTAPDF_ERROR_ARGUMENT);CHECK(c==0);CHECK(quantapdf_form_field_name(NULL,0,&s,&n)==QUANTAPDF_ERROR_ARGUMENT);CHECK(s==NULL&&n==0);quantapdf_drop_form(NULL);}
static void test_empty_and_non_pdf(void){quantapdf_document *d=NULL;expect_empty(NO_ACROFORM_PDF);expect_empty(ACROFORM_NO_FIELDS_PDF);expect_empty(ACROFORM_EMPTY_FIELDS_PDF);CHECK(quantapdf_open(NON_PDF,NULL,&d)==QUANTAPDF_ERROR_FORMAT);CHECK(d==NULL);}

static void expect_structure_info(const quantapdf_form *f,size_t i){quantapdf_form_field_info x={0};x.struct_size=sizeof(x);CHECK(quantapdf_form_field_get_info(f,i,&x)==QUANTAPDF_OK);CHECK(x.type==QUANTAPDF_FORM_FIELD_TEXT);CHECK(x.flags==0);CHECK(x.value_presence==QUANTAPDF_FORM_VALUE_MISSING);CHECK(x.value_count==0);CHECK(x.option_count==0);CHECK(x.widget_count==0);}
static void test_structure(void){quantapdf_document *d=NULL;quantapdf_form *f=NULL;size_t c=99;CHECK(quantapdf_open(ACROFORM_STRUCTURE_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);CHECK(quantapdf_form_field_count(f,&c)==QUANTAPDF_OK);CHECK(c==4);CHECK(quantapdf_form_widget_count(f,&c)==QUANTAPDF_OK);CHECK(c==0);expect_structure_info(f,0);expect_string(f,0,0,"profile.nickname",1);expect_string(f,0,1,"Profile label",1);expect_structure_info(f,1);expect_string(f,1,0,"repeat",1);expect_string(f,1,1,"",0);expect_structure_info(f,2);expect_string(f,2,0,"",0);expect_structure_info(f,3);expect_string(f,3,0,"",1);quantapdf_drop_form(f);quantapdf_close(d);expect_extract_status(ACROFORM_BAD_ROOT_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_FIELDS_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_KID_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_CYCLE_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_REPEATED_NODE_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_PARENT_MISMATCH_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_ROOT_PARENT_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_DEPTH_257_PDF,QUANTAPDF_ERROR_UNSUPPORTED);expect_extract_status(ACROFORM_MIXED_GROUP_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_GROUP_CONFLICT_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_DUPLICATE_NAME_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_PERIOD_NAME_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_FT_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_FF_PDF,QUANTAPDF_ERROR_FORMAT);}

static void expect_widget_field(const quantapdf_form *f,size_t i,quantapdf_form_field_type t,quantapdf_form_value_presence p,size_t o,size_t w){quantapdf_form_field_info x={0};x.struct_size=sizeof(x);CHECK(quantapdf_form_field_get_info(f,i,&x)==QUANTAPDF_OK);CHECK(x.type==t);CHECK(x.value_presence==p);CHECK(x.value_count==0);CHECK(x.option_count==o);CHECK(x.widget_count==w);}
static void expect_button_option(const quantapdf_form *f,size_t i,size_t o){quantapdf_form_option_info x={0};x.struct_size=sizeof(x);CHECK(quantapdf_form_field_option_get_info(f,i,o,&x)==QUANTAPDF_OK);CHECK(x.kind==QUANTAPDF_FORM_OPTION_BUTTON_STATE);}
static void expect_widget(const quantapdf_form *f,size_t i,size_t field,int page,float x0,float y0,float x1,float y1,uint32_t flags,size_t opt){quantapdf_form_widget_info x={0};x.struct_size=sizeof(x);CHECK(quantapdf_form_widget_get_info(f,i,&x)==QUANTAPDF_OK);CHECK(x.field_index==field);CHECK(x.page_index==page);CHECK(close_float(x.bounds.x0,x0));CHECK(close_float(x.bounds.y0,y0));CHECK(close_float(x.bounds.x1,x1));CHECK(close_float(x.bounds.y1,y1));CHECK(x.flags==flags);CHECK(x.button_option_index==opt);}
static void test_widgets(void){quantapdf_document *d=NULL;quantapdf_form *f=NULL;size_t c=99;CHECK(quantapdf_open(ACROFORM_WIDGETS_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);CHECK(quantapdf_form_field_count(f,&c)==QUANTAPDF_OK);CHECK(c==4);CHECK(quantapdf_form_widget_count(f,&c)==QUANTAPDF_OK);CHECK(c==7);expect_widget_field(f,0,QUANTAPDF_FORM_FIELD_TEXT,QUANTAPDF_FORM_VALUE_MISSING,0,1);expect_widget_field(f,1,QUANTAPDF_FORM_FIELD_CHECKBOX,QUANTAPDF_FORM_VALUE_MISSING,1,2);expect_widget_field(f,2,QUANTAPDF_FORM_FIELD_RADIO_BUTTON,QUANTAPDF_FORM_VALUE_MISSING,2,3);expect_widget_field(f,3,QUANTAPDF_FORM_FIELD_UNKNOWN,QUANTAPDF_FORM_VALUE_NOT_APPLICABLE,0,1);expect_button_option(f,1,0);expect_button_option(f,2,0);expect_button_option(f,2,1);expect_widget(f,0,0,0,10,10,40,30,0,SIZE_MAX);expect_widget(f,1,1,0,50,10,70,30,0,0);expect_widget(f,2,2,0,80,10,100,30,0,0);expect_widget(f,3,1,1,10,10,30,30,UINT32_C(2147483649),0);expect_widget(f,4,2,1,40,10,60,30,0,1);expect_widget(f,5,3,1,70,10,100,30,0,SIZE_MAX);expect_widget(f,6,2,2,10,10,30,30,0,0);quantapdf_drop_form(f);quantapdf_close(d);CHECK(quantapdf_open(ACROFORM_ANNOTS_NONARRAY_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);CHECK(quantapdf_form_widget_count(f,&c)==QUANTAPDF_OK);CHECK(c==0);quantapdf_drop_form(f);quantapdf_close(d);expect_extract_status(ACROFORM_BAD_BUTTON_AP_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_ORPHAN_WIDGET_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_MISSING_WIDGET_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_DUPLICATE_WIDGET_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_P_MISMATCH_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_DIRECT_WIDGET_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_WIDGET_RECT_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_WIDGET_FLAGS_PDF,QUANTAPDF_ERROR_FORMAT);}

static void expect_scalar_field(const quantapdf_form *f,size_t i,quantapdf_form_field_type t,quantapdf_form_value_presence p,size_t values,int signed_state){quantapdf_form_field_info x={0};x.struct_size=sizeof(x);CHECK(quantapdf_form_field_get_info(f,i,&x)==QUANTAPDF_OK);CHECK(x.type==t);CHECK(x.value_presence==p);CHECK(x.value_count==values);CHECK(x.option_count==0);CHECK(x.is_signed==signed_state);}
static void expect_utf8_value(const quantapdf_form *f,size_t i,size_t vi,const char *e){quantapdf_form_value_info x={0};const char *s=(const char *)(uintptr_t)1;size_t n=99;x.struct_size=sizeof(x);CHECK(quantapdf_form_field_value_get_info(f,i,vi,&x)==QUANTAPDF_OK);CHECK(x.kind==QUANTAPDF_FORM_VALUE_UTF8);CHECK(x.option_index==SIZE_MAX);CHECK(quantapdf_form_field_value_utf8(f,i,vi,&s,&n)==QUANTAPDF_OK);CHECK(s!=NULL);CHECK(n==strlen(e));CHECK(memcmp(s,e,n)==0);CHECK(s[n]=='\0');}
static void test_scalar_values_and_full_api(void){quantapdf_document *d=NULL;quantapdf_form *f=NULL;size_t c=99;quantapdf_form_field_info small={0},info={0};CHECK(quantapdf_open(ACROFORM_SCALARS_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);CHECK(quantapdf_form_field_count(f,&c)==QUANTAPDF_OK);CHECK(c==7);expect_scalar_field(f,0,QUANTAPDF_FORM_FIELD_TEXT,QUANTAPDF_FORM_VALUE_MISSING,0,0);expect_scalar_field(f,1,QUANTAPDF_FORM_FIELD_TEXT,QUANTAPDF_FORM_VALUE_PRESENT,1,0);expect_utf8_value(f,1,0,"");expect_scalar_field(f,2,QUANTAPDF_FORM_FIELD_TEXT,QUANTAPDF_FORM_VALUE_PRESENT,1,0);expect_utf8_value(f,2,0,"hello");expect_string(f,2,1,"",1);expect_scalar_field(f,3,QUANTAPDF_FORM_FIELD_PUSH_BUTTON,QUANTAPDF_FORM_VALUE_NOT_APPLICABLE,0,0);expect_scalar_field(f,4,QUANTAPDF_FORM_FIELD_SIGNATURE,QUANTAPDF_FORM_VALUE_NOT_APPLICABLE,0,0);expect_scalar_field(f,5,QUANTAPDF_FORM_FIELD_SIGNATURE,QUANTAPDF_FORM_VALUE_NOT_APPLICABLE,0,1);expect_scalar_field(f,6,QUANTAPDF_FORM_FIELD_UNKNOWN,QUANTAPDF_FORM_VALUE_NOT_APPLICABLE,0,0);small.struct_size=offsetof(quantapdf_form_field_info,is_signed);CHECK(quantapdf_form_field_get_info(f,0,&small)==QUANTAPDF_ERROR_ARGUMENT);info.struct_size=sizeof(info);info.type=QUANTAPDF_FORM_FIELD_SIGNATURE;info.flags=UINT32_MAX;CHECK(quantapdf_form_field_get_info(f,99,&info)==QUANTAPDF_ERROR_ARGUMENT);CHECK(info.type==QUANTAPDF_FORM_FIELD_UNKNOWN);CHECK(info.flags==0);quantapdf_drop_form(f);quantapdf_close(d);expect_extract_status(ACROFORM_BAD_VALUE_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_SIGNATURE_PDF,QUANTAPDF_ERROR_FORMAT);}

static void expect_choice_field(const quantapdf_form *f,size_t i,quantapdf_form_field_type t,uint32_t flags,size_t options,size_t values,int multi){quantapdf_form_field_info x={0};x.struct_size=sizeof(x);CHECK(quantapdf_form_field_get_info(f,i,&x)==QUANTAPDF_OK);CHECK(x.type==t);CHECK(x.flags==flags);CHECK(x.value_presence==QUANTAPDF_FORM_VALUE_PRESENT);CHECK(x.option_count==options);CHECK(x.value_count==values);CHECK(x.is_multiselect==multi);}
static void expect_choice_option(const quantapdf_form *f,size_t field,size_t option,const char *export_text,const char *display_text){quantapdf_form_option_info oi={0};const char *s=NULL;size_t n=0;oi.struct_size=sizeof(oi);CHECK(quantapdf_form_field_option_get_info(f,field,option,&oi)==QUANTAPDF_OK);CHECK(oi.kind==QUANTAPDF_FORM_OPTION_CHOICE);CHECK(quantapdf_form_field_option_export(f,field,option,&s,&n)==QUANTAPDF_OK);CHECK(n==strlen(export_text));CHECK(memcmp(s,export_text,n)==0);CHECK(quantapdf_form_field_option_display(f,field,option,&s,&n)==QUANTAPDF_OK);CHECK(n==strlen(display_text));CHECK(memcmp(s,display_text,n)==0);}
static void expect_option_value(const quantapdf_form *f,size_t field,size_t value_index,size_t option_index){quantapdf_form_value_info v={0};const char *s=(const char *)(uintptr_t)1;size_t n=99;v.struct_size=sizeof(v);CHECK(quantapdf_form_field_value_get_info(f,field,value_index,&v)==QUANTAPDF_OK);CHECK(v.kind==QUANTAPDF_FORM_VALUE_OPTION);CHECK(v.option_index==option_index);CHECK(quantapdf_form_field_value_utf8(f,field,value_index,&s,&n)==QUANTAPDF_ERROR_UNSUPPORTED);CHECK(s==NULL);CHECK(n==0);}
static void test_choice_values(void){quantapdf_document *d=NULL;quantapdf_form *f=NULL;size_t c=99;CHECK(quantapdf_open(ACROFORM_CHOICE_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);CHECK(quantapdf_form_field_count(f,&c)==QUANTAPDF_OK);CHECK(c==4);expect_choice_field(f,0,QUANTAPDF_FORM_FIELD_COMBO_BOX,UINT32_C(131072),2,1,0);expect_choice_option(f,0,0,"US","United States");expect_choice_option(f,0,1,"JP","Japan");expect_option_value(f,0,0,1);expect_choice_field(f,1,QUANTAPDF_FORM_FIELD_COMBO_BOX,UINT32_C(393216),2,1,0);expect_choice_option(f,1,0,"Tokyo","Tokyo");expect_choice_option(f,1,1,"Osaka","Osaka");expect_utf8_value(f,1,0,"Kyoto");expect_choice_field(f,2,QUANTAPDF_FORM_FIELD_LIST_BOX,0,3,1,0);expect_choice_option(f,2,1,"M","M");expect_option_value(f,2,0,1);expect_choice_field(f,3,QUANTAPDF_FORM_FIELD_LIST_BOX,UINT32_C(2097152),3,2,1);expect_choice_option(f,3,0,"r","Red");expect_choice_option(f,3,2,"b","Blue");expect_option_value(f,3,0,0);expect_option_value(f,3,1,2);quantapdf_drop_form(f);quantapdf_close(d);expect_extract_status(ACROFORM_BAD_OPT_PDF,QUANTAPDF_ERROR_FORMAT);expect_extract_status(ACROFORM_BAD_I_PDF,QUANTAPDF_ERROR_FORMAT);}

static void test_button_values(void)
{quantapdf_document *d=NULL;quantapdf_form *f=NULL;quantapdf_form_field_info info={0};size_t count=0;CHECK(quantapdf_open(ACROFORM_MAIN_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&f)==QUANTAPDF_OK);info.struct_size=sizeof(info);CHECK(quantapdf_form_field_get_info(f,7,&info)==QUANTAPDF_OK);CHECK(info.type==QUANTAPDF_FORM_FIELD_CHECKBOX);CHECK(info.value_presence==QUANTAPDF_FORM_VALUE_PRESENT);CHECK(info.option_count==1);CHECK(info.value_count==1);expect_option_value(f,7,0,0);CHECK(quantapdf_form_field_get_info(f,8,&info)==QUANTAPDF_OK);CHECK(info.type==QUANTAPDF_FORM_FIELD_RADIO_BUTTON);CHECK(info.value_presence==QUANTAPDF_FORM_VALUE_PRESENT);CHECK(info.option_count==2);CHECK(info.value_count==1);expect_option_value(f,8,0,1);CHECK(quantapdf_form_field_count(f,&count)==QUANTAPDF_OK);CHECK(count==17);CHECK(quantapdf_form_widget_count(f,&count)==QUANTAPDF_OK);CHECK(count==16);quantapdf_drop_form(f);quantapdf_close(d);}

static void test_lifetime_atomicity_no_execution(void)
{quantapdf_document *d=NULL;quantapdf_form *a=NULL,*b=NULL;size_t count=0;int sentinel=0;CHECK(quantapdf_open(ACROFORM_MAIN_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&a)==QUANTAPDF_OK);quantapdf_close(d);CHECK(quantapdf_form_field_count(a,&count)==QUANTAPDF_OK);CHECK(count==17);expect_string(a,0,0,"profile.nickname",1);expect_utf8_value(a,0,0,"Ada");expect_utf8_value(a,1,0,"same");CHECK(quantapdf_form_widget_count(a,&count)==QUANTAPDF_OK);CHECK(count==16);quantapdf_drop_form(a);
CHECK(quantapdf_open(ACROFORM_JS_PDF,NULL,&d)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&a)==QUANTAPDF_OK);CHECK(quantapdf_document_form(d,&b)==QUANTAPDF_OK);quantapdf_close(d);expect_utf8_value(a,0,0,"SAFE");expect_utf8_value(a,1,0,"UNCHANGED");expect_utf8_value(b,0,0,"SAFE");expect_utf8_value(b,1,0,"UNCHANGED");quantapdf_drop_form(a);quantapdf_drop_form(b);
CHECK(quantapdf_open(ACROFORM_STREAM_VALUE_PDF,NULL,&d)==QUANTAPDF_OK);a=(quantapdf_form *)&sentinel;CHECK(quantapdf_document_form(d,&a)==QUANTAPDF_ERROR_FORMAT);CHECK(a==NULL);a=(quantapdf_form *)&sentinel;CHECK(quantapdf_document_form(d,&a)==QUANTAPDF_ERROR_FORMAT);CHECK(a==NULL);quantapdf_close(d);
CHECK(quantapdf_open(ACROFORM_LATE_MALFORMED_PDF,NULL,&d)==QUANTAPDF_OK);a=(quantapdf_form *)&sentinel;CHECK(quantapdf_document_form(d,&a)==QUANTAPDF_ERROR_FORMAT);CHECK(a==NULL);a=(quantapdf_form *)&sentinel;CHECK(quantapdf_document_form(d,&a)==QUANTAPDF_ERROR_FORMAT);CHECK(a==NULL);quantapdf_close(d);}

static void run_case(const char *name){if(strcmp(name,"api-shell")==0)test_api_shell();else if(strcmp(name,"empty")==0)test_empty_and_non_pdf();else if(strcmp(name,"structure")==0)test_structure();else if(strcmp(name,"widgets")==0)test_widgets();else if(strcmp(name,"scalar-values")==0)test_scalar_values_and_full_api();else if(strcmp(name,"choice-values")==0)test_choice_values();else if(strcmp(name,"button-values")==0)test_button_values();else if(strcmp(name,"lifetime")==0)test_lifetime_atomicity_no_execution();else CHECK(0);}
int main(int argc,char **argv){compile_surface();if(argc==3&&strcmp(argv[1],"--case")==0){run_case(argv[2]);return EXIT_SUCCESS;}CHECK(argc==1);test_api_shell();test_empty_and_non_pdf();test_structure();test_widgets();test_scalar_values_and_full_api();test_choice_values();test_button_values();test_lifetime_atomicity_no_execution();return EXIT_SUCCESS;}
